---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/pets/outside_zone_count":
    get:
      summary: outside_zone_count pet
      responses:
        '200':
          description: successful
  "/api/v1/pets":
    get:
      summary: list pets
      responses:
        '200':
          description: successful
    post:
      summary: create pet
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
